"""approval_overrides_table

Revision ID: 64208cb2a826
Revises: b3f1c8a2d904
Create Date: 2026-06-27 09:31:09.909662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64208cb2a826'
down_revision: Union[str, None] = 'b3f1c8a2d904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('violation', sa.Text(), nullable=False),
    sa.Column('overridden_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('competitor_listings_listing_id_key'), 'competitor_listings', type_='unique')
    op.drop_index(op.f('ix_competitor_listings_listing_id'), table_name='competitor_listings')
    op.create_index(op.f('ix_competitor_listings_listing_id'), 'competitor_listings', ['listing_id'], unique=True)
    op.drop_constraint(op.f('competitor_shops_shop_id_key'), 'competitor_shops', type_='unique')
    op.drop_index(op.f('ix_competitor_shops_shop_id'), table_name='competitor_shops')
    op.create_index(op.f('ix_competitor_shops_shop_id'), 'competitor_shops', ['shop_id'], unique=True)
    op.drop_constraint(op.f('keyword_research_keyword_key'), 'keyword_research', type_='unique')
    op.drop_index(op.f('ix_keyword_research_keyword'), table_name='keyword_research')
    op.create_index(op.f('ix_keyword_research_keyword'), 'keyword_research', ['keyword'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keyword_research_keyword'), table_name='keyword_research')
    op.create_index(op.f('ix_keyword_research_keyword'), 'keyword_research', ['keyword'], unique=False)
    op.create_unique_constraint(op.f('keyword_research_keyword_key'), 'keyword_research', ['keyword'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_competitor_shops_shop_id'), table_name='competitor_shops')
    op.create_index(op.f('ix_competitor_shops_shop_id'), 'competitor_shops', ['shop_id'], unique=False)
    op.create_unique_constraint(op.f('competitor_shops_shop_id_key'), 'competitor_shops', ['shop_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_competitor_listings_listing_id'), table_name='competitor_listings')
    op.create_index(op.f('ix_competitor_listings_listing_id'), 'competitor_listings', ['listing_id'], unique=False)
    op.create_unique_constraint(op.f('competitor_listings_listing_id_key'), 'competitor_listings', ['listing_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('approval_overrides')
    # ### end Alembic commands ###
