"""initial

Revision ID: ea9c2eee784d
Revises: 
Create Date: 2026-06-27 01:21:09.265127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea9c2eee784d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_pool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=True),
    sa.Column('carrier_pillar', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=20), nullable=False),
    sa.Column('carrier_pillar', sa.String(length=20), nullable=False),
    sa.Column('user_provided_title', sa.String(length=255), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('has_stone', sa.Boolean(), nullable=True),
    sa.Column('stone_type', sa.String(length=100), nullable=True),
    sa.Column('shape', sa.String(length=50), nullable=True),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('occasion', sa.String(length=100), nullable=True),
    sa.Column('recipient', sa.String(length=50), nullable=True),
    sa.Column('size_info', sa.Text(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('generated_variants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_title', sa.String(length=140), nullable=True),
    sa.Column('final_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_description', sa.Text(), nullable=True),
    sa.Column('selected_variant_id', sa.String(length=10), nullable=True),
    sa.Column('etsy_listing_id', sa.String(length=50), nullable=True),
    sa.Column('etsy_section_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('image_workflow_used', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('is_real', sa.Boolean(), nullable=True),
    sa.Column('workflow_source', sa.String(length=20), nullable=True),
    sa.Column('alt_text', sa.String(length=250), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('favorites', sa.Integer(), nullable=True),
    sa.Column('cart_adds', sa.Integer(), nullable=True),
    sa.Column('sales', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_stats')
    op.drop_table('product_images')
    op.drop_table('products')
    op.drop_table('keyword_pool')
    # ### end Alembic commands ###
